name: $name
version: $version
description: A simple Skript addon for disguising players/entities into other entities
author: _tud

website: https://github.com/UnderscoreTud/diskuise
api-version: 1.19

main: ${group}.Diskuise
softdepend: [ Skript, LibsDisguises, ProtocolLib ]
